/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Omar_Mohamed (https://sketchfab.com/Omar_Mohamed)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/airplane-628232dd846249f6a89ed3fb2e1cd4f5
title: Airplane
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three';

// Offset so correct for model initial positon compared to earth
const AIRPLANE_ROTATE_OFFSET = -Math.PI / 2;

export default function Airplane({ planeRotation, position }) {

  const { rotation } = useSpring({
    rotation: [Math.PI / 2, planeRotation + AIRPLANE_ROTATE_OFFSET, 0]
  });

  const { nodes, materials } = useGLTF('/airplane.gltf')

  return (
    <a.group transparent position={position} scale={[0.01, 0.01, 0.01]} rotation={rotation} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Cylinder" position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
            <group name="Cylinder001" position={[0, 0, 1.8]} rotation={[0, 0, 0]} scale={[0.3, 0.3, 0.3]}>
              <mesh geometry={nodes.Cylinder001_Material005_0.geometry} material={materials['Material.005']} />
              <mesh
                geometry={nodes.Cylinder001_Material003_0.geometry}
                material={nodes.Cylinder001_Material003_0.material}
              />
            </group>
            <mesh geometry={nodes.Cylinder_Material003_0.geometry} material={nodes.Cylinder_Material003_0.material} />
            <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group position={[487.22, 868.26, 779]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/scene.gltf')
