/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Omar_Mohamed (https://sketchfab.com/Omar_Mohamed)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/airplane-628232dd846249f6a89ed3fb2e1cd4f5
title: Airplane
*/

import { useGLTF } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'
import { useEffect } from 'react'

export default function Model({ position, rotation, markerId }) {
  const { nodes, materials } = useGLTF('/plane.gltf')

  const { scale } = useSpring({
    from: { scale: 0 },
    to: { scale: 0.01 },
    config: { duration: 500 }
  })

  const { planeRotation } = useSpring({
    planeRotation: [Math.PI / 2, rotation, 0]
  })

  useEffect(() => {
    scale.reset()
    materials['Material.001'].color = {
      r: parseInt(markerId.slice(0, 2), 16) / 256,
      g: parseInt(markerId.slice(2, 4), 16) / 256,
      b: parseInt(markerId.slice(4, 6), 16) / 256,
    }
  }, [markerId])

  return (
    <a.group position={position} rotation={planeRotation} scale={scale} dispose={null}>
      <group name="RootNode">
        <group name="Cylinder" position={[0, 0, 0]} scale={1}>
          <group name="Cylinder001" position={[0, 0, 1.8]} scale={0.3}>
            <mesh name="Cylinder001_Material005_0" geometry={nodes.Cylinder001_Material005_0.geometry} material={materials['Material.005']} />
            <mesh name="Cylinder001_Material003_0" geometry={nodes.Cylinder001_Material003_0.geometry} material={materials['Material.003']} />
          </group>
          <mesh name="Cylinder_Material003_0" geometry={nodes.Cylinder_Material003_0.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder_Material001_0" geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder_Material002_0" geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder_Material004_0" geometry={nodes.Cylinder_Material004_0.geometry} material={materials['Material.004']} />
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/plane.gltf')
